version: '3'

volumes:
  mongo_data:
    driver: local

services:
  nginx:
    image: nginx:1.17.10
    volumes:
      #- ./nginx/nginx-local.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx-local-all.conf:/etc/nginx/nginx.conf
      - ./nginx/config:/etc/ssl
    ports:
      - 443:443
    depends_on:
      - api
  
  frontend:
    image: iguide_frontend
    build:
      dockerfile: ./docker/Dockerfile-frontend
    volumes:
      - ./frontend:/app
    ports:
      - 5001:5001
    restart: unless-stopped
    depends_on:
      - api

  api:
    image: iguide_api
    volumes:
      - ./api:/app/api
      - ./tests:/app/tests
      - ./.env:/app/.env
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2
  
  catalog-trigger:
    image: iguide_trigger
    volumes:
      - ./api:/app/api
      - ./triggers:/app/triggers
      - ./.env:/app/.env
    build:
      context: ./docker/
      dockerfile: Dockerfile-triggers
    command: >
      python triggers/update_catalog.py
    restart: on-failure
    depends_on:
      - mongodb
  
  typeahead-trigger:
    image: iguide_trigger
    volumes:
      - ./api:/app/api
      - ./triggers:/app/triggers
      - ./.env:/app/.env
    build:
      context: ./docker/
      dockerfile: Dockerfile-triggers
    command: >
      python triggers/update_typeahead.py
    restart: on-failure
    depends_on:
      - mongodb
