version: '3'

volumes:
  mongo_data:
    driver: local

services:
  nginx:
    image: nginx:1.17.10
    volumes:
      - ./nginx/nginx-local.conf:/etc/nginx/nginx.conf
      - ./nginx/config:/etc/ssl
    ports:
      - 443:443
    depends_on:
      - api

  api:
    image: iguide_api
    volumes:
      - ./api:/app/api
      - ./tests:/app/tests
      - ./.env:/app/.env
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    restart: on-failure
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2
