---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: iguide
spec:
  domains:
  - IGUIDE_DOMAIN
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: iguide
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iguide
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: IGUIDE_IP
    networking.gke.io/v1beta1.FrontendConfig: iguide
    networking.gke.io/managed-certificates: iguide
spec:
  defaultBackend:
    service:
      name: frontend
      port:
        number: 80
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: api
            port:
              number: 80
      - pathType: Prefix
        path: "/docs"
        backend:
          service:
            name: api
            port:
              number: 80
      - pathType: Prefix
        path: "/redoc"
        backend:
          service:
            name: api
            port:
              number: 80
      - pathType: Prefix
        path: "/openapi.json"
        backend:
          service:
            name: api
            port:
              number: 80
